version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1-buster-slim
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo "npm installing"
            - run: npm install
            - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:12.16.1-buster-slim
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo "testing stuff"
            - run: npm install
            - run: npm test
workflows:
  build-and-test:
    jobs:
      - build
      - test
